services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    command: ["start-dev"]
    environment:
      - KC_DB=dev-file
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin123456
      - KC_HEALTH_ENABLED=true
    ports:
      - "8090:8080"
      - "9000:9000"
    healthcheck:
      test:
        - "CMD-SHELL"
        - |
          exec 3<>/dev/tcp/127.0.0.1/9000; \
          echo -e "GET /health/ready HTTP/1.1\r\nHost: localhost\r\n\r\n" >&3; \
          grep -q "HTTP/1.1 200 OK" <&3
      interval: 5s
      timeout: 5s
      retries: 20

  init-keycloak:
    image: quay.io/keycloak/keycloak:26.3
    depends_on:
      keycloak:
        condition: service_healthy
      # FIXME: broken in podman: https://github.com/containers/podman-compose/issues/575
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - KCADM_PATH=/opt/keycloak/bin/kcadm.sh
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123456
      - REALM=trustify
      - INIT_DATA=/init-sso/data
      - TRUSTIFY_ADMIN=admin
      - TRUSTIFY_ADMIN_PASSWORD=admin123456
      - REDIRECT_URIS=["http://localhost:*"]
      - WALKER_SECRET=ZVzq9AMOVUdMY1lSohpx1jI3aW56QDPS
      # The internal name (between containers) is "keycloak". However, from the host it reachable as "localhost:8090".
      # So the "frontend" needs to be set to that
      - SSO_FRONTEND_URL=http://localhost:8090
      # GitHub OAuth provider configuration
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
    volumes:
      - ./config/init-sso:/init-sso${SELINUX_VOLUME_OPTIONS}
    entrypoint: /usr/bin/bash
    command: /init-sso/init.sh
